---
title: "LoadingData"
author: "Alina Kline-Schoder"
date: "`r Sys.Date()`"
output: html_document
---
# CAM
```{r}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
library(ggnewscale)
library(Seurat)
library(ggplot2)
library(cowplot)
library(dplyr)
library(circlize)
library(scales)
library(stringr)
library(viridis)
library(patchwork)
library(ComplexHeatmap)
library(ggrepel)

source("/media/alina/Backup1/Scripts/R/Visium/Ontology.R")
setwd("/media/alina/Backup1/Scripts/R/2022_SavedData/")
source("/media/alina/Backup1/Scripts/R/Visium/ScatterPlot_AKS.R")
source("/media/alina/Backup1/Scripts/R/Visium/Treemap_AKS.R")
source("/media/alina/Backup1/Scripts/R/Visium/AK_SpatialPlot.R")
load("Visium-Integrated.rdata")
load("3-Microglia.rdata")
MG<-c("X0","X1","X2","X3","X4","X5","X8","Perivascular.macrophages")
Microglia$Treatment<-factor(Microglia$Treatment,levels = c("Naive","FUS+MB","FUS-BBBO","FUS"))
Microglia$Full<-factor(Microglia$Full,levels=c("WT Naive","AD Naive","WT FUS+MB","AD FUS+MB","WT FUS-BBBO","AD FUS-BBBO","WT FUS","AD FUS"))
DefaultAssay(Microglia) <- "integrated"
Microglia <- ScaleData(Microglia, verbose = FALSE)
Microglia <- RunPCA(Microglia, npcs = 50, verbose = FALSE)
Microglia <- RunUMAP(Microglia, reduction = "pca", dims = 1:15)
Microglia <- FindNeighbors(Microglia, dims = 1:15)
Microglia <- FindClusters(Microglia, resolution = 0.5)

TaxDef<-read.csv("/media/alina/Backup1/Scripts/R/2022_NewSeq/TaxRef.csv")
TaxDef<-rbind(TaxDef,data.frame(X=NA,TaxonomyRank1="Immune cells",TaxonomyRank2="Immune cells",TaxonomyRank3="Immune cells",TaxonomyRank4=c("X0","X1","X2","X3","X4","X5","X6")))
rownames(TaxDef)<-str_replace_all(TaxDef$TaxonomyRank4,' ','.')
rownames(TaxDef)<-str_replace_all(rownames(TaxDef),'-','.')
TaxDef[c("Non.glutamatergic.neuroblasts","Glutamatergic.neuroblasts"),"TaxonomyRank2"]<-"Neuroblast"
TaxDef[TaxDef$TaxonomyRank1=="Glia","TaxonomyRank2"]<-"Glia"
#TaxDef[grepl("Telencephalon",TaxDef$TaxonomyRank3),"TaxonomyRank2"]<-"Telencephalon"

ColorsClusters<-c("#C13A13",
                  "#DD9D56",
                  "#EBCE78", # green
                  "#F8FF99", # green
                  "#CEE790", # IAM
                  "#A4CF86",
                  "#509F72")# DAM
ColorsGroup<-c("white","white","#BC6290","white")

col_fun = colorRamp2(c(-2, 0, 2), c("blue", "#D3D3D3", "red"))
```
# barplot
```{r}
tab<-as.data.frame(table(Microglia$Full,Microglia$seurat_clusters))
tot<-as.data.frame(table(Microglia$Full))
tab$Freq_Norm<-tab$Freq/tot[tab$Var1,]$Freq*100
tab$Genotype<-recode(tab$Var1,"WT Naive"="WT","AD Naive"="AD","WT FUS"="WT","AD FUS"="AD","WT FUS+MB"="WT","AD FUS+MB"="AD","WT FUS-BBBO"="WT","AD FUS-BBBO"="AD")
tab$Treatment<-recode(tab$Var1,"WT Naive"="Naive","AD Naive"="Naive","WT FUS"="FUS","AD FUS"="FUS","WT FUS+MB"="FUS+MB","AD FUS+MB"="FUS+MB","WT FUS-BBBO"="FUS-BBBO","AD FUS-BBBO"="FUS-BBBO")

Barplot2<-ggplot(tab,aes(x=Freq_Norm,y=Treatment))+geom_bar(stat="identity",aes(fill=Var2),position = position_stack(reverse = TRUE))+scale_fill_manual(values=ColorsClusters)+scale_y_discrete(expand = c(0,0))+new_scale_fill()+geom_tile(aes(y=Treatment,x=-2,fill=Treatment),width=4,color="black")+scale_fill_manual(values=ColorsGroup)+facet_grid(Genotype~.)+theme_bw()+xlab("Cluster (%)")+theme(legend.position = "none",axis.title.y = element_blank())+scale_x_continuous(expand = c(0,0))+theme(strip.background = element_rect(fill="white"))+theme(axis.text.y = element_text(size = 8))
```


```{r}
UMAP<-DimPlot(Microglia,group.by = "seurat_clusters",label=T,cols=ColorsClusters,label.box = T)+theme(legend.position = "none",plot.title = element_blank())+theme(axis.text = element_blank(),axis.ticks = element_blank(),axis.title = element_blank())
```
# Vis plots
```{r}
VisCAM<-AK_SpatialPl(brain.merge,features="Perivascular.macrophages",image.alpha = 0,stroke = NA,pt.size.factor = 3,ncol=4,plotnames = c("WT Naive","WT FUS-BBBO","AD Naive","AD FUS-BBBO",alpha=1),max.cutoff = 0.75)&theme(legend.position = "none",plot.title = element_text(size=8))&coord_flip()

t<-data.frame(x=1:10,y=1:10)
LegCAM<-get_legend(ggplot(t,aes(x=x,y=x,fill=x/10))+geom_point()+scale_fill_viridis(guide = "colourbar", limits = c(0,1),breaks=c(0,0.5,1),values=c(0,0.5,1),option="A")+guides(fill=guide_colorbar(title="CAM",title.hjust = 0.5,direction = "horizontal",barwidth = unit(4,"cm"),barheight = unit(0.1,"cm"),title.position = "top",label.position = "bottom"))+theme(legend.title = element_text(size=8)))

```

```{r}
ColorsLines<-c("black","#81375D")

Long<-cbind(brain.merge@meta.data[,c("Perivascular.macrophages","Vascular.and.leptomeningeal.cells")],brain.merge$Genotype,brain.merge$Treatment)
colnames(Long)<-c("Perivascular.macrophages","Vascular.and.leptomeningeal.cells","Genotype","Treatment")
formula <- y ~ x


Long$Genotype<-factor(recode(Long$Genotype,"3xtg"="AD"),levels=c("WT","AD"))

Long$Treatment<-factor(recode(Long$Treatment,"FUS"="FUS-BBBO"),levels=c("Naive","FUS-BBBO"))
shapes<-as.numeric(recode(Long$Genotype,"AD"=15,"WT"=16))
color<-recode(Long$Treatment,"Naive"="black","FUS-BBBO"=ColorsGroup[3])
Long$color<-color
library(grid)
library(ggpmisc)
library(broom)
formula <- y ~ x
FullPlot<-ggplot(Long,aes(x=Perivascular.macrophages,y=Vascular.and.leptomeningeal.cells,color=color))+geom_point(shape=shapes,size=1,color=color)+facet_grid(Genotype~.)+geom_smooth(method="lm",fullrange=TRUE,size=0.5,se=FALSE) + stat_poly_eq(aes(label = paste(..rr.label..)), label.x = c(0.1,0.5), label.y = 0.95,
formula = formula, parse = TRUE, size = 3) + stat_fit_glance(method = 'lm', method.args = list(formula = formula),geom = 'text_npc', aes(label = paste("P = ", signif(..p.value.., digits = 2), sep = "")),label.x = c(0.1,0.5), label.y = 0.7, size = 3)+theme_bw()+theme(legend.position = "none")+coord_cartesian(expand=FALSE)+xlab("CAM")+ylab("Vascular Cells")+theme(axis.title = element_text(size=8),panel.background = element_rect(fill="white"),panel.grid = element_blank(),strip.background = element_rect(fill="white"))+scale_color_manual(values=ColorsLines)+theme(plot.margin = margin(0.25,0.5,0.25,0.5,"cm"))
```


```{r}
VisCAM_Full<-plot_grid(LegCAM,VisCAM,rel_heights = c(0.25,1),nrow=2)

Right<-plot_grid(VisCAM_Full,FullPlot,nrow=2,rel_heights = c(1,1),labels = c("g","h"))

Left<-plot_grid(UMAP+theme(plot.margin = margin(0.25,0.25,0.25,0.5,"cm")),Barplot2+theme(plot.margin = margin(0.25,0.25,0.25,0.5,"cm"),axis.title = element_text(size=8)),nrow=2,labels = c("e","f"))
plot_grid(Left,Right,nrow=1,rel_widths = c(1,1.5))
ggsave("/media/alina/Backup1/Scripts/R/Visium/Figures/Presub_bottom.png",width = 8.5,height=4,units = "in",bg="white")

```


